# https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/
version: '3'
services:
  jobmanager:
    image: flink:1.12-scala_2.12-java8
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:1.12-scala_2.12-java8
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  sql-client:
    image: flink:1.12-scala_2.12-java8
    command: bin/sql-client.sh embedded
    depends_on:
      - jobmanager
    volumes:
      - ./target/flink-udf-in-go-1.0-SNAPSHOT-jar-with-dependencies.jar:/opt/flink/lib/flink-udf-in-go-1.0-SNAPSHOT-jar-with-dependencies.jar
    environment:
      # jna debug log
      #- JAVA_TOOL_OPTIONS="-Djna.debug_load=true -Djna.debug_load.jna=true"
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
